### ISSUE TITLE
Sagas are executed before the reducer was called

### ISSUE THREAD

**Issue by mlegenhausen** [CodeSequence/store-saga#1]
Since 0.0.3 the sagas seemed to be called before the reducer proceeded on the action.

**Comment by MikeRyanDev** [comment]
:+1: Confirmed. Let me get some tests written this weekend and I'll restore the original behavior.

**Comment by MikeRyanDev** [comment]
Never mind, I needed this fixed this morning. Released v0.0.4, should address this.

**Comment by mlegenhausen** [comment]
Thanks for the quick fix :) Works again.
