### ISSUE TITLE
No provider! :(

### ISSUE THREAD

**Issue by wizardnet972** [CodeSequence/store-saga#14]
Hi all,

I getting error when I try to inject my model (aka action creator) into createSaga.

I getting no provider for StudentModel.

```
EXCEPTION: Error: Uncaught (in promise): EXCEPTION: Error during instantiation of Token ngrx/store/post-middleware! (School -> Student -> Store -> StoreBackend -> Token ngrx/store/resolved-post-middleware -> Token ngrx/store/post-middleware).
ORIGINAL EXCEPTION: No provider for Student! (Token @ngrx/store Saga Effect -> Student)
```

Saga file:

```
export const loginEffect = createSaga(function(http: Http, student: Student) {
..............
}, [ Http, Student ]);
```

any ideas?

**Comment by MikeRyanDev** [comment]
You need to provide your `Student` service. Include it in your list of provided when you bootstrap your application:

``` ts
bootstrap(App, [
  provideStore(...),
  installSagaMiddleware(...),
  Student
]);
```

**Comment by wizardnet972** [comment]
Hi @MikeRyan52, 
I did that, but now I'm getting a different error:

`
ORIGINAL EXCEPTION: Cannot instantiate cyclic dependency! (Token @ngrx/store Saga Effect -> Student -> Store -> StoreBackend -> Token ngrx/store/resolved-post-middleware)`

in my Student class I have constructor:

`constructor(private store: Store<IStudent>, private api: ApiService, private applicationState: ApplicationState) {.....................}
`

**Comment by abdulhaq-e** [comment]
You can find a closed issue that is exactly similar. I opened it then closed it after I figured what is happening.

You are adding `Student` as a dependency to `loginEffect`. Your `Student` service relies on `Store`, however, the `loginEffect` (and all sagas) also rely on `Store` and this is causing a '_cyclic dependency_'.

You cannot inject any service for a saga that has the `Store` injected into it.
