### ISSUE TITLE
@Injectable() ?

### ISSUE THREAD

**Issue by wmaurer** [CodeSequence/store-saga#2]
I really like this Saga implementation, and am about to give it a go in my current ng2 project.
I also like that the Sagas are functions, as there's no need for using classes here.

Would it be possible to have the dependency injection work without having to supply the array of dependencies as the second argument to `createSaga`? Or is it so that the `@Injectable()` decorator only works with classes?

**Comment by MikeRyanDev** [comment]
I wish you didn't have to supply dependencies :( But yeah, as you've guessed the `@Injectable()` decorator doesn't work with functions (yet). There are early proposals to bring function decorators to the language in addition to class decorators, so hopefully it is only temporary.

**Comment by wmaurer** [comment]
Thanks for the quick reply!
