### ISSUE TITLE
Discussion: Library renaming

### ISSUE THREAD

**Issue by frederikschubert** [CodeSequence/store-saga#22]
To move our [discussion](https://github.com/CodeSequence/store-saga/issues/17) to a proper issue... :)

**Comment by frederikschubert** [comment]
Current proposals:

@ngrx/:
- effects
- side-effects
- aftermath
- backlash
- reaction
- store-side-effects

**Comment by nosachamos** [comment]
@ngrx/side-effects sounds great

**Comment by frederikschubert** [comment]
The library has been renamed to [@ngrx/effects](https://github.com/ngrx/effects).
