### ISSUE TITLE
Sagas do not dispatch generated actions

### ISSUE THREAD

**Issue by mlegenhausen** [CodeSequence/store-saga#3]
After porting from version 0.0.4 to 1.0.0-beta.6. 

The sagas receive actions from the dispatcher then generate the side effect and the resulting action is generated but never dispatched.

I also wonder if it is possible to call `installSagaMiddleware` multiple times?

**Comment by MikeRyanDev** [comment]
Can you post an example of your saga? As long as you are returning your new action stream, the saga middleware will connect it to the dispatcher.

**Comment by mlegenhausen** [comment]
Sorry for this sloppy issue. Until now I hadn't the time to dig into the problem.

The main cause why my porting didn't work is that I get two different `Dispatcher` instances. One is used by the sagas and the other one is used by my application. I don't know why currently.

I am using `angular2@2.0.0-beta.13`, `rxjs@5.0.0-beta.4` and `store-saga@1.0.0-beta.8`.

**Comment by mlegenhausen** [comment]
Ok I investigated further and found out that the child/parent `SagaRunner` instances use different dispatchers. Is this intended? This seems to me the problem why I can't get anything back from my dispatcher.

Do you have an example application where I can see the current implementation running? Cause even when I reduce my application to have one saga that should simply dispatch an example action it never touches my reducer.

**Comment by ksachdeva** [comment]
Facing the similar issues. Not able to dispatch the actions from the saga.

**Comment by ksachdeva** [comment]
Created a small sample to showcase the issue but not able to produce it. Here is a small and simple project showing the use case.

[https://github.com/ksachdeva/angular2-store-saga-example](https://github.com/ksachdeva/angular2-store-saga-example)

Need to now investigate what is going wrong in my relatively bigger project :(

**Comment by Merott** [comment]
Having the same issue...

**Comment by ksachdeva** [comment]
Hi Merott,

Check out my repository (https://github.com/ksachdeva/angular2-store-saga-example); I am not having the issue in this example at least. Tonight I am going to look at the app where I am having issue and see what is different. At least in this simple app the issue is not there.

Regards
Kapil

**Comment by MikeRyanDev** [comment]
Is it possible that you might be providing the store multiple times? That's the only way I can imagine StoreRunner would grab a different dispatcher.

**Comment by ksachdeva** [comment]
I had checked that and made sure that it was not the case. However, I am able to reproduce the problem in a (relatively) smaller example. In couple of hours ...am going to upload the repository showing the problematic situation and may be you will be able to see what is wrong as I am not able to.

**Comment by ksachdeva** [comment]
Hi Mike,

Here is a link to the repo where I have successfully reproduced the issue -

https://github.com/ksachdeva/store-saga-issue

This is a very simple ionic app. The ReadMe has the instructions on how to download and run it. I tried to create a plunker but ran into systemjs related issues so unfortunately you would have to clone the repo and run it locally.

Now in the source code you would not see anywhere call to bootstrap as it is the Ionic framework doing it. The entry point of the app is a component that is decorated using @App. I have looked into the source code of @App decorator and it does take what is provided in providers and push them when doing bootstrap ( )

In this example (and is similar to what I did for https://github.com/ksachdeva/angular2-store-saga-example) when you press the decrement button then a saga (asyncsags2) kicks in; the sage makes an Http call and then issues an increment action. The example shows that the Http call does kick in however the increment action is not dispatched. This is shown in this video as well - http://screencast.com/t/T2FZE8TTwCl

After tinkering with the app, I figured that if I provide the providers on the component (Page in ionic) then it does work. In order to do it, you would want to comment the providers in app.ts and uncomment the providers in pages/page1/page1.ts. Now I get the expect response. Here is the video for that - 
http://screencast.com/t/hBGHC0ZO 

The part that does not make sense is that even though the providers have been passed to boostrap, some actions indeed do dispatch but the very last action from saga fails to dispatch.

Would appreciate if you can help as many other people are facing the issue as well in their respective applications.

Regards & thanks
Kapil

**Comment by Merott** [comment]
Thank you @ksachdeva for doing this. We have Ionic in common. I've been digging for hours already, but I guess I'll keep digging...

**Comment by Merott** [comment]
Still digging...

If it helps, here is the list of providers that are passed into Angular's `bootstrap` function:

**https://github.com/ksachdeva/angular2-store-saga-example**

<img width="376" alt="screen shot 2016-04-22 at 00 34 21" src="https://cloud.githubusercontent.com/assets/1757708/14727440/cbed0368-0822-11e6-8041-3e8792ae8ebf.png">

**https://github.com/ksachdeva/store-saga-issue**

<img width="354" alt="screen shot 2016-04-22 at 00 30 36" src="https://cloud.githubusercontent.com/assets/1757708/14727450/e0024f84-0822-11e6-870a-4f4dde6c557f.png">

Interesting that for `angular2-store-saga-example`, in which the Saga actions work as expected, there are two entries with token `@ngrx/store/sagas Bootstrap`. Why is that?

**Comment by ksachdeva** [comment]
Interesting @Merott ....would appreciate if you could share the technique of how you printed it; I thought there is no built in logging in angular 2 yet or did you patch it by hand and then printed it

**Comment by mlegenhausen** [comment]
This is what I experienced too. Especially the `Dispatcher` class gets instantiated twice.

**Comment by MikeRyanDev** [comment]
@ksachdeva Thank you for the detailed explanation and sample repository. I pulled it down last night but I am only able to reproduce the bug _occasionally_. Sometimes it works as expected. This is making me lean towards it being a zone issue. I'll keep you posted.

@mlegenhausen Are you also using Ionic?

**Comment by mlegenhausen** [comment]
@MikeRyan52 yes

**Comment by ksachdeva** [comment]
Hi Mike,

Thanks for taking a look at it. I am surprised that you are able to reproduce the bug occasionally as for me it is systematic and is always the case i.e. in this saga 

```
const asyncEffect2 = createSaga(function sagaFactory(http: Http) {

  return function loginSaga(iteration$: Observable<any>) {
    return iteration$
      .filter(iteration => iteration.action.type === DECREMENT)
      .map(iteration => iteration.action.payload)
      .mergeMap(payload => {
        return http.get(BASE_WEB_URL + 'posts/1')
          .map(res => {
            return {
              type: INCREMENT,
              payload: res.json()
            }
          })
          .catch(err => {
            return Observable.of({
              type: 'DECREMENT',
              payload: err.json()
            });
          });
      });
  };

}, [Http]);
```

The http call does happen but the INCREMENT action "never" happens.

Regards
Kapil

**Comment by Merott** [comment]
> Interesting @Merott ....would appreciate if you could share the technique of how you printed it; I thought there is no built in logging in angular 2 yet or did you patch it by hand and then printed it

@ksachdeva - Nothing special. I set a breakpoint on the line of call to `bootstrap`, then ran this:

``` js
flatten = (arr) => arr.reduce((a, b) =>
    a.concat(Array.isArray(b) ? flatten(b) : b), []);

flatten(providers)
  .map(p => p.token ? (p.token.name || p.token._desc) : p.toString().split('\n')[0])
  .forEach(p => console.log(p))
```

@MikeRyan52 - I can definitely reproduce the issue consistently - Do you have any pointers as to where to start debugging from?

**Comment by ksachdeva** [comment]
Hi Mike,

Did you get some cycle to reproduce/test the issue ?

Currently I am using "sort of sagas" using my own custom service (which requires more setup) but doing it using your middleware is a preferred option for me.

Regards & thanks
Kapil

**Comment by MikeRyanDev** [comment]
@ksachdeva It seems to be a bug with how injectors are created for child components in Ionic. I'm still trying to solve it.

**Comment by ksachdeva** [comment]
Hi Mike,

Any update on this; I have updated the https://github.com/ksachdeva/store-saga-issue to angular 2 rc1 and ionic beta 7. The issue is still there.

Regards & thanks
Kapil

**Comment by Merott** [comment]
I think I'm having a similar issue with @ngrx/effects, or maybe not. All I know is that [`connectEffectsToDispatcher`](https://github.com/ngrx/effects/blob/7f576a6e9e81a9a73bda5bcc5106abacc92edd27/lib/effects.ts#L20) gets a different instance of the `Dispatcher` than the `Store` gets...

**Comment by MikeRyanDev** [comment]
This is still a bug that I can't seem to isolate :/ 

Would love some help figuring it out. This issue also affects the new ngrx/effects lib

**Comment by Merott** [comment]
I'm talking about @ngrx/effects here. I don't know, maybe this issue needs to be moved there. Until we figure out the cause of the problem, I guess we won't know which repo it belongs in. Anyway...

The store is clearly being instantiated twice: once as a dependency of `connectEffectsToStore`, during the application bootstrap, and again after the application has bootstrapped. I've recorded a video of one of my debugging sessions, which shows how the store being instantiated twice. The bit that I find most interesting is at the end of the video, where there are two properties relating to the store. That seems wrong to me. However, I honestly have no idea what that means and how or if that's supposed to help us with anything... I'm lost. <a href="http://merott.com/files/ngrx-effects-store-twice.mp4" target="_blank">Here is the video</a>.

For now, to work around the issue, as you may have noticed in the video, I'm patching the Store constructor with this horrible hack:

``` js
var Store = (function (_super) {
    let __store, __state$;   // for the hack below...
    __extends(Store, _super);
    function Store(_dispatcher, _reducer, state$, initialState) {
        var _this = this;
        _super.call(this, initialState);
        this._dispatcher = _dispatcher;
        this._reducer = _reducer;
        this.select = select_1.select.bind(this);

        /*=================================================================
        hack to work around issue with two instances of store being created
        =================================================================*/
        if(__store) {
          Object.assign(this, __store);
          state$ = __state$;
        } else {
          __store = this;
          __state$ = state$;
        }
        /*===============================================================*/

        state$.subscribe(function(state) { return _super.prototype.next.call(_this, state); });
    }

// ...
```

**Comment by Merott** [comment]
This can be closed now. Ionic 2 Beta 8 fixes it.

**Comment by ksachdeva** [comment]
Hi Merott,

Since they have not released the beta 8, could you please provide the link to which changeset in Ionic is fixing the behavior so that I can understand what was causing the issue in the first place.

Regards & thanks
Kapil

**Comment by Merott** [comment]
@ksachdeva - they've done a major refactor, and dropped the custom `App` decorator (and `Page` too), instead opting for the `ionicBootstrap` function that works like Angular's `bootstrap`. So, we may never find out what was causing the issue in the first place 😄 .

Here is the issue to track: https://github.com/driftyco/ionic/issues/6685

**Comment by MikeRyanDev** [comment]
Looks like this has been fixed since Ionic 2 beta 8
