### ISSUE TITLE
installation problems

### ISSUE THREAD

**Issue by select** [CodeSequence/store-saga#4]
Hey there I have some issues installing/upgrading with angular beta 13 and store-saga. While `angular2@2.0.0-beta.13 requires a peer of rxjs@5.0.0-beta.2` store sage complains `store-saga@1.0.0-beta.6 requires a peer of rxjs@^5.0.0-beta.3`
whatever version I install one or the other is complaining

I got it to install by first installing everything without store-saga and then installing store-saga, but now I face the following error 

```
Module not found: Error: Cannot resolve module 'rxjs/scheduler/async' in /home/select/Dev/shoutr-srv/client/node_modules/store-saga
```

**Comment by MikeRyanDev** [comment]
Yes, store-saga requires rxjs beta 3 or higher (that's the release that introduced the async scheduler). 

While Angular 2 has a locked dependency on beta 2, it has been my experience that it works just fine with beta 3 installed.

**Comment by select** [comment]
Ok thanks I also realized that this are just warnings and not errors
