### ISSUE TITLE
Update Angular2 version

### ISSUE THREAD

**Issue by BaruchFisherman** [CodeSequence/store-saga#9]
Hi,
Can you please update Angular2 version to the latest?
Currently saga uses Angular2 beta 8 and the current Angular2 version is beta 12.

**Comment by BaruchFisherman** [comment]
And the documentation is wrong - createSaga doesn't exists.

**Comment by MikeRyanDev** [comment]
@BaruchFisherman The docs and updates are actually on a beta tag. Install store-saga like this:

```
npm install store-saga@latest --save
```

**Comment by BaruchFisherman** [comment]
@MikeRyan52 Great!! Thank You!!
